// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import type { PluginListenerHandle } from '@capacitor/core';
import { WebPlugin } from '@capacitor/core';

import type { AdMobPlusPlugin, AdmobConsentInfo } from './definitions';
import type { AdMobPlusEventName, AdMobPlusEventPayloadMap } from './events';

export class AdMobPlusWeb extends WebPlugin implements AdMobPlusPlugin {
  addListener<E extends AdMobPlusEventName>(
    eventName: E,
    listenerFunc: (event: AdMobPlusEventPayloadMap[E]) => void,
  ): Promise<PluginListenerHandle> & PluginListenerHandle {
    return super.addListener(eventName, listenerFunc) as Promise<PluginListenerHandle> & PluginListenerHandle;
  }

  async start(...opts: Parameters<AdMobPlusPlugin['start']>): ReturnType<AdMobPlusPlugin['start']> {
    console.log('start', opts);
  }

  async configure(...opts: Parameters<AdMobPlusPlugin['configure']>): ReturnType<AdMobPlusPlugin['configure']> {
    console.log('configure', opts);
  }

  async configRequest(
    ...opts: Parameters<AdMobPlusPlugin['configRequest']>
  ): ReturnType<AdMobPlusPlugin['configRequest']> {
    console.log('configRequest', opts);
  }

  async requestConsentInfo(
    ...opts: Parameters<AdMobPlusPlugin['requestConsentInfo']>
  ): ReturnType<AdMobPlusPlugin['requestConsentInfo']> {
    console.log('requestConsentInfo', opts);
    return {
      status: 'NOT_REQUIRED' as AdmobConsentInfo['status'],
      isConsentFormAvailable: false,
      canRequestAds: true,
      privacyOptionsRequirementStatus: 'NOT_REQUIRED' as AdmobConsentInfo['privacyOptionsRequirementStatus'],
    };
  }

  async showConsentForm(): ReturnType<AdMobPlusPlugin['showConsentForm']> {
    console.log('showConsentForm');
    return {
      status: 'NOT_REQUIRED' as AdmobConsentInfo['status'],
      canRequestAds: true,
      privacyOptionsRequirementStatus: 'NOT_REQUIRED' as AdmobConsentInfo['privacyOptionsRequirementStatus'],
    };
  }

  async showPrivacyOptionsForm(): ReturnType<AdMobPlusPlugin['showPrivacyOptionsForm']> {
    console.log('showPrivacyOptionsForm');
  }

  async adCreate(...opts: Parameters<AdMobPlusPlugin['adCreate']>): ReturnType<AdMobPlusPlugin['adCreate']> {
    console.log('adCreate', opts);
  }

  async adIsLoaded(...opts: Parameters<AdMobPlusPlugin['adIsLoaded']>): ReturnType<AdMobPlusPlugin['adIsLoaded']> {
    console.log('adIsLoaded', opts);
    return false;
  }

  async adLoad(...opts: Parameters<AdMobPlusPlugin['adLoad']>): ReturnType<AdMobPlusPlugin['adLoad']> {
    console.log('adLoad', opts);
  }

  async adShow(...opts: Parameters<AdMobPlusPlugin['adShow']>): ReturnType<AdMobPlusPlugin['adShow']> {
    console.log('adShow', opts);
  }

  async adHide(...opts: Parameters<AdMobPlusPlugin['adHide']>): ReturnType<AdMobPlusPlugin['adHide']> {
    console.log('adHide', opts);
  }

  async feedAdCreate(
    ...opts: Parameters<AdMobPlusPlugin['feedAdCreate']>
  ): ReturnType<AdMobPlusPlugin['feedAdCreate']> {
    console.log('feedAdCreate', opts);
    return { id: 1 };
  }

  async feedAdDestroy(
    ...opts: Parameters<AdMobPlusPlugin['feedAdDestroy']>
  ): ReturnType<AdMobPlusPlugin['feedAdDestroy']> {
    console.log('feedAdDestroy', opts);
  }

  async feedAdLoad(...opts: Parameters<AdMobPlusPlugin['feedAdLoad']>): ReturnType<AdMobPlusPlugin['feedAdLoad']> {
    console.log('feedAdLoad', opts);
  }

  async feedAdIsLoaded(
    ...opts: Parameters<AdMobPlusPlugin['feedAdIsLoaded']>
  ): ReturnType<AdMobPlusPlugin['feedAdIsLoaded']> {
    console.log('feedAdIsLoaded', opts);
    return false;
  }

  async feedAdUpdateBounds(
    ...opts: Parameters<AdMobPlusPlugin['feedAdUpdateBounds']>
  ): ReturnType<AdMobPlusPlugin['feedAdUpdateBounds']> {
    console.log('feedAdUpdateBounds', opts);
  }

  async feedAdSetAutoRefresh(
    ...opts: Parameters<AdMobPlusPlugin['feedAdSetAutoRefresh']>
  ): ReturnType<AdMobPlusPlugin['feedAdSetAutoRefresh']> {
    console.log('feedAdSetAutoRefresh', opts);
  }

  async trackingAuthorizationStatus(
    ...opts: Parameters<AdMobPlusPlugin['trackingAuthorizationStatus']>
  ): ReturnType<AdMobPlusPlugin['trackingAuthorizationStatus']> {
    console.log('trackingAuthorizationStatus', opts);
    return { status: false };
  }

  async requestTrackingAuthorization(
    ...opts: Parameters<AdMobPlusPlugin['requestTrackingAuthorization']>
  ): ReturnType<AdMobPlusPlugin['requestTrackingAuthorization']> {
    console.log('requestTrackingAuthorization', opts);
    return { status: false };
  }

  async getPluginVersion(): Promise<{ version: string }> {
    return { version: 'web' };
  }
}
